Update Fetch JIJI.yml

diff --git a/.github/workflows/Fetch JIJI.yml b/.github/workflows/Fetch JIJI.yml
--- a/.github/workflows/Fetch JIJI.yml
+++ b/.github/workflows/Fetch JIJI.yml
@@ -1,4 +1,4 @@
-name: Fetch JIJI Sitemaps
+name: Fetch JIJI
 
 on:
   schedule:
@@ -63,18 +63,15 @@ jobs:
         for url in "${urls[@]}"
         do
           suffix=$(basename $url .xml)  # '.xml' 拡張子を取り除く
-          if wget $url -O "xml_jiji_$(date +\%Y\%m)/xml-jiji_$(date +\%Y\%m%d)_$suffix.xml"; then
-            echo "Downloaded $url"
-          else
-            echo "Failed to download $url"
-            wget $url -O "xml_jiji_$(date +\%Y\%m)/xml-jiji_$(date +\%Y\%m%d)_$suffix.xml"  # エラー時にもう一度試行
-          fi
+          wget $url -O "xml_jiji_$(date +\%Y\%m)/xml-jiji_$(date +\%Y\%m%d)_$suffix.xml" || echo "Failed to download $url" >> download_errors.log
+          sleep 3  # 各ダウンロードの間に3秒待機
         done
 
     - name: Commit and Push files to main
+      if: success() || failure()  # 成功か失敗に関係なく実行
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
-        git add xml_jiji_$(date +\%Y\%m)/*
-        git commit -m "Add XML files for $(date +\%Y\%m%d)"
+        git add xml_jiji_$(date +\%Y\%m)/* download_errors.log || true
+        git commit -m "Add XML files for $(date +\%Y\%m%d) with possible errors"
         git push origin main
